Repository worldbank/gld, pull requests merged in 2021-06, with the labels that each got.

#6 Merge Tom's files to GLD develop-merge branch
  GLD/BRA/BRA_MAIN.do
  GLD/GLD_I2D2_MAIN.do
  GLD/IND/IND_MAIN.do
  GLD/MEX/MEX_MAIN.do
  GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
  GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
  GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
  GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
  GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
  GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
  GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS.do
  GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
  GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
  GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
  GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
  GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
  GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
  GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
  GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
  GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
  GLD/PHL/PHL_MAIN.do
  GLD/PHL/v1.0/I2D2/PHL_1997_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_1998_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_1999_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2000_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2001_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2002_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2003_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2004_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2005_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2006_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2007_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2008_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2009_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2010_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2011_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2012_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2013_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2014_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2015_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2017_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2018_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2019_I2D2_LFS.do
  GLD/ZAF/ZAF_MAIN.do
Labels: organize

#22 fix Industry Codes
  GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
  GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
  GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
  GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
  GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
  GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
  GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS.do
  GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
  GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
  GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
  GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
  GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
  GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
  GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
  GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
  GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
  GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_I2D2/Programs/PHL_2013_I2D2_LFS.do
  GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_I2D2/Programs/PHL_2014_I2D2_LFS.do
  GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_I2D2/Programs/PHL_2015_I2D2_LFS.do
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
Labels: variable coding

#26 incorporate multiscript label solution
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS_labels.R
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/README.md
  GLD/PHL/PHL_MAIN.do
Labels: variable coding

#32 R code to create metadata
  GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
  GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
  GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
  GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
  GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
  GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
  GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS.do
  GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
  GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
  GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
  GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
  GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
  GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
  GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
  GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
  GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
  GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_I2D2/Programs/PHL_2013_I2D2_LFS.do
  GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_I2D2/Programs/PHL_2014_I2D2_LFS.do
  GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_I2D2/Programs/PHL_2015_I2D2_LFS.do
  GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_I2D2/Programs/Placeholder.do
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
  GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_I2D2/Programs/PHL_2018_I2D2_LFS.do
  GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_I2D2/Programs/PHL_2019_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_1997_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_1998_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_1999_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2000_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2001_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2002_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2003_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2004_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2005_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2006_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2007_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2008_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2009_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2010_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2011_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2012_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2013_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2014_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2015_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2017_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2018_I2D2_LFS.do
  GLD/PHL/v1.0/I2D2/PHL_2019_I2D2_LFS.do
  Support/Global/label_tools.R
  Support/Global/survey_metadata.R
Labels: enhancement, organize

#31 Loop in section "8.13 labour cleanup"
  Support/Templates/GLD_Harmonization_Template.do
Labels: GLD

#40 Region codes
  GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
  GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
  GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
  GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
  GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
  GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
  GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
  GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
  GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
  GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
  GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
  GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
  GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
  GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
  GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
  GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_I2D2/Programs/PHL_2013_I2D2_LFS.do
  GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_I2D2/Programs/PHL_2014_I2D2_LFS.do
  GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_I2D2/Programs/PHL_2015_I2D2_LFS.do
  GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
  GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_I2D2/Programs/PHL_2018_I2D2_LFS.do
  GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_I2D2/Programs/PHL_2019_I2D2_LFS.do
  Support/Global/label_tools.R
  Support/Guides and Documentation/Administrative_Levels.md
  Support/Guides and Documentation/Education_Levels.md
  Support/Guides and Documentation/I2D2_Geographic_Nomenclature.md
  Support/Guides and Documentation/Region_Recode_Checks.Rmd
Labels: variable coding
